version: '3.4'

services:
  rankingcandidatos.api:
    image: ${DOCKER_REGISTRY-}rankingcandidatosapi
    build:
      context: .
      dockerfile: rankingcandidatos.API/Dockerfile
    ports:
        - "80:80" 
        - "443:443"

