name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: docker logout
        run: docker logout
      - name: docker login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
   
  publish:
    needs: login
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Build Image
        run: docker build . --file ./rankingcandidatos.API/Dockerfile -t rankingcandidatos/api:main
      - name: Tag Image
        run: docker tag rankingcandidatos/api:main rankingcandidatos/api:latest
      - name: Push Image
        run: docker push rankingcandidatos/api:latest
