name: Publicar Imagem Docker
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  steps:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
        with:
          ref: master
      - name: docker build
        run: docker build . --file ./rankingcandidatos.API/Dockerfile -t rankingcandidatos/api:main
      - name: docker tag
        run: docker tag rankingcandidatos/api:main rankingcandidatos/api:latest
      - name: docker login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} 
      - name: docker push
        run: docker push rankingcandidatos/api:latest
