name: Publish Dockerhub
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

jobs:
    build-api:
        runs-on: ubuntu-latest 
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v2
            with:
                ref: main
          - name: docker build
            run: docker build . --file ./src/rankingcandidatos.API/Dockerfile -t rankingcandidatos/api:main
          - name: docker tag
            run: docker tag rankingcandidatos/api:main rankingcandidatos/api:latest
          - name: docker login
            run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin 
          - name: docker push
            run: docker push rankingcandidatos/api:latest
